### ISSUE TITLE
supporting HEAD requests

### ISSUE THREAD

**Issue by zeke** [avinoamr/connect-slashes#12]
Hi @avinoamr 👋 

We're happily using this module for the Electron website and the new help.github.com. Thanks for writing it!

We've noticed some redirect issues in our application, and I suspect it's because this module only handles GET requests. Would you open to a change to add support for HEAD requests?

https://github.com/avinoamr/connect-slashes/blob/eb86b6f43c63c872872c8fb327dd0ed3eb43ce1e/lib/connect-slashes.js#L40

**Comment by avinoamr** [comment]
@zeke that's exciting to hear that you and github are using it :)

Absolutely. I will add all "read-only" http methods: GET, HEAD and OPTIONS.

**Comment by zeke** [comment]
Hey thanks for the quick response! I preemptively opened a PR without seeing your comment. I will amend it to include support for OPTIONS 👍

**Comment by avinoamr** [comment]
@zeke published. 1.4.0

**Comment by zeke** [comment]
Thanks @avinoamr  🙌
